/**
 * Generated by orval 🍺
 * Do not edit manually.
 * adhocly-server
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery,
  useQueryClient
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  InvalidateOptions,
  MutationFunction,
  MutationFunctionContext,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { apiFetch } from '../api-fetch';
export interface Task {
  completed: boolean;
  createdAt: string;
  /** @nullable */
  dueOn?: string | null;
  id: string;
  /** @nullable */
  plannedFor?: string | null;
  project: string;
  /** @nullable */
  repeatWeekday?: number | null;
  title: string;
  updatedAt: string;
}

export interface TaskInput {
  completed: boolean;
  /** @nullable */
  dueOn?: string | null;
  id: string;
  /** @nullable */
  plannedFor?: string | null;
  project: string;
  /** @nullable */
  repeatWeekday?: number | null;
  title: string;
}

export interface ToggleInput {
  completed: boolean;
}

export interface ToggleResult {
  nextTask?: null | Task;
  task: Task;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type listTasksResponse200 = {
  data: Task[]
  status: 200
}

export type listTasksResponseSuccess = (listTasksResponse200) & {
  headers: Headers;
};
;

export type listTasksResponse = (listTasksResponseSuccess)

export const getListTasksUrl = () => {




  return `/api/tasks`
}

export const listTasks = async ( options?: Parameters<typeof apiFetch>[1]): Promise<listTasksResponse> => {

  return apiFetch<listTasksResponse>(getListTasksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTasksQueryKey = () => {
    return [
    `/api/tasks`
    ] as const;
    }


export const getListTasksQueryOptions = <TData = Awaited<ReturnType<typeof listTasks>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTasksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasks>>> = ({ signal }) => listTasks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTasksQueryResult = NonNullable<Awaited<ReturnType<typeof listTasks>>>
export type ListTasksQueryError = unknown



export function createListTasks<TData = Awaited<ReturnType<typeof listTasks>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListTasksQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createListTasks} query
 */
export const invalidateListTasks = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() }, options);

  return queryClient;
}





export type createTaskResponse201 = {
  data: Task
  status: 201
}

export type createTaskResponse400 = {
  data: string
  status: 400
}

export type createTaskResponseSuccess = (createTaskResponse201) & {
  headers: Headers;
};
export type createTaskResponseError = (createTaskResponse400) & {
  headers: Headers;
};

export type createTaskResponse = (createTaskResponseSuccess | createTaskResponseError)

export const getCreateTaskUrl = () => {




  return `/api/tasks`
}

export const createTask = async (taskInput: TaskInput, options?: Parameters<typeof apiFetch>[1]): Promise<createTaskResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<createTaskResponse>(getCreateTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(taskInput)
  }
);}





export const getCreateTaskMutationKey = () => ['createTask'] as const;

export const getCreateTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,CreateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,CreateTaskMutationVariables, TContext> => {

const mutationKey = getCreateTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTask>>, CreateTaskMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTask(data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof createTask>>, variables: CreateTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type CreateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof createTask>>>
    export type CreateTaskMutationBody = TaskInput
    export type CreateTaskMutationError = string
    export type CreateTaskMutationVariables = {data: TaskInput}

    export const createCreateTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,CreateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createTask>>,
        TError,
        CreateTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getCreateTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type getTaskResponse200 = {
  data: Task
  status: 200
}

export type getTaskResponse404 = {
  data: string
  status: 404
}

export type getTaskResponseSuccess = (getTaskResponse200) & {
  headers: Headers;
};
export type getTaskResponseError = (getTaskResponse404) & {
  headers: Headers;
};

export type getTaskResponse = (getTaskResponseSuccess | getTaskResponseError)

export const getGetTaskUrl = (id: string,) => {




  return `/api/tasks/${id}`
}

export const getTask = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<getTaskResponse> => {

  return apiFetch<getTaskResponse>(getGetTaskUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTaskQueryKey = (id: string,) => {
    return [
    `/api/tasks/${id}`
    ] as const;
    }


export const getGetTaskQueryOptions = <TData = Awaited<ReturnType<typeof getTask>>, TError = string>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({ signal }) => getTask(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getTask>>>
export type GetTaskQueryError = string



export function createGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = string>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getGetTaskQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createGetTask} query
 */
export const invalidateGetTask = async (
 queryClient: QueryClient, id: string, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetTaskQueryKey(id) }, options);

  return queryClient;
}





export type updateTaskResponse200 = {
  data: Task
  status: 200
}

export type updateTaskResponse400 = {
  data: string
  status: 400
}

export type updateTaskResponse404 = {
  data: string
  status: 404
}

export type updateTaskResponseSuccess = (updateTaskResponse200) & {
  headers: Headers;
};
export type updateTaskResponseError = (updateTaskResponse400 | updateTaskResponse404) & {
  headers: Headers;
};

export type updateTaskResponse = (updateTaskResponseSuccess | updateTaskResponseError)

export const getUpdateTaskUrl = (id: string,) => {




  return `/api/tasks/${id}`
}

export const updateTask = async (id: string,
    taskInput: TaskInput, options?: Parameters<typeof apiFetch>[1]): Promise<updateTaskResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<updateTaskResponse>(getUpdateTaskUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(taskInput)
  }
);}





export const getUpdateTaskMutationKey = () => ['updateTask'] as const;

export const getUpdateTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,UpdateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,UpdateTaskMutationVariables, TContext> => {

const mutationKey = getUpdateTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTask>>, UpdateTaskMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateTask(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof updateTask>>, variables: UpdateTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type UpdateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof updateTask>>>
    export type UpdateTaskMutationBody = TaskInput
    export type UpdateTaskMutationError = string
    export type UpdateTaskMutationVariables = {id: string;data: TaskInput}

    export const createUpdateTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,UpdateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updateTask>>,
        TError,
        UpdateTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getUpdateTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type deleteTaskResponse204 = {
  data: void
  status: 204
}

export type deleteTaskResponse404 = {
  data: string
  status: 404
}

export type deleteTaskResponseSuccess = (deleteTaskResponse204) & {
  headers: Headers;
};
export type deleteTaskResponseError = (deleteTaskResponse404) & {
  headers: Headers;
};

export type deleteTaskResponse = (deleteTaskResponseSuccess | deleteTaskResponseError)

export const getDeleteTaskUrl = (id: string,) => {




  return `/api/tasks/${id}`
}

export const deleteTask = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<deleteTaskResponse> => {

  return apiFetch<deleteTaskResponse>(getDeleteTaskUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTaskMutationKey = () => ['deleteTask'] as const;

export const getDeleteTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,DeleteTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,DeleteTaskMutationVariables, TContext> => {

const mutationKey = getDeleteTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTask>>, DeleteTaskMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteTask(id,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof deleteTask>>, variables: DeleteTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type DeleteTaskMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTask>>>

    export type DeleteTaskMutationError = string
    export type DeleteTaskMutationVariables = {id: string}

    export const createDeleteTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,DeleteTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteTask>>,
        TError,
        DeleteTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getDeleteTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type toggleTaskResponse200 = {
  data: ToggleResult
  status: 200
}

export type toggleTaskResponse404 = {
  data: string
  status: 404
}

export type toggleTaskResponseSuccess = (toggleTaskResponse200) & {
  headers: Headers;
};
export type toggleTaskResponseError = (toggleTaskResponse404) & {
  headers: Headers;
};

export type toggleTaskResponse = (toggleTaskResponseSuccess | toggleTaskResponseError)

export const getToggleTaskUrl = (id: string,) => {




  return `/api/tasks/${id}/toggle`
}

export const toggleTask = async (id: string,
    toggleInput: ToggleInput, options?: Parameters<typeof apiFetch>[1]): Promise<toggleTaskResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<toggleTaskResponse>(getToggleTaskUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(toggleInput)
  }
);}





export const getToggleTaskMutationKey = () => ['toggleTask'] as const;

export const getToggleTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof toggleTask>>, TError,ToggleTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof toggleTask>>, TError,ToggleTaskMutationVariables, TContext> => {

const mutationKey = getToggleTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleTask>>, ToggleTaskMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  toggleTask(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof toggleTask>>, variables: ToggleTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type ToggleTaskMutationResult = NonNullable<Awaited<ReturnType<typeof toggleTask>>>
    export type ToggleTaskMutationBody = ToggleInput
    export type ToggleTaskMutationError = string
    export type ToggleTaskMutationVariables = {id: string;data: ToggleInput}

    export const createToggleTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof toggleTask>>, TError,ToggleTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof toggleTask>>,
        TError,
        ToggleTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getToggleTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type healthResponse200 = {
  data: void
  status: 200
}

export type healthResponse503 = {
  data: string
  status: 503
}

export type healthResponseSuccess = (healthResponse200) & {
  headers: Headers;
};
export type healthResponseError = (healthResponse503) & {
  headers: Headers;
};

export type healthResponse = (healthResponseSuccess | healthResponseError)

export const getHealthUrl = () => {




  return `/health`
}

export const health = async ( options?: Parameters<typeof apiFetch>[1]): Promise<healthResponse> => {

  return apiFetch<healthResponse>(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthQueryOptions = <TData = Awaited<ReturnType<typeof health>>, TError = string>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) => health({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>
export type HealthQueryError = string



export function createHealth<TData = Awaited<ReturnType<typeof health>>, TError = string>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getHealthQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createHealth} query
 */
export const invalidateHealth = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getHealthQueryKey() }, options);

  return queryClient;
}
