/**
 * Generated by orval 🍺
 * Do not edit manually.
 * adhocly-server
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery,
  matchQuery,
  useQueryClient
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  InvalidateOptions,
  MutationFunction,
  MutationFunctionContext,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { apiFetch } from '../api-fetch.ts';
export interface BTreeMap {[key: string]: number}

export type FieldKind = typeof FieldKind[keyof typeof FieldKind];


export const FieldKind = {
  text: 'text',
  number: 'number',
  choice: 'choice',
} as const;

export interface Folder {
  createdAt: string;
  id: string;
  name: string;
  /**
     * `None` is the top level; folders nest to any depth.
     * @nullable
     */
  parentId?: string | null;
  updatedAt: string;
}

export interface FolderInput {
  /**
     * Optional client-selected entity id; sync uses a separate mutation id for safe replay.
     * @nullable
     */
  id?: string | null;
  name: string;
  /**
     * Omitted or null creates/moves the folder at the top level.
     * @nullable
     */
  parentId?: string | null;
}

export interface MetadataField {
  createdAt: string;
  id: string;
  kind: FieldKind;
  name: string;
  options: string[];
}

export interface MetadataFieldInput {
  /**
     * Optional client-selected entity id; sync uses a separate mutation id for safe replay.
     * @nullable
     */
  id?: string | null;
  kind: FieldKind;
  name: string;
  options?: string[];
}

export interface MetadataFieldUpdate {
  name: string;
  options?: string[];
}

export interface MetadataValue {
  fieldId: string;
  value: string;
}

export interface MetadataValueInput {
  /**
     * Omit or send null/blank to clear the value.
     * @nullable
     */
  value?: string | null;
}

export interface Project {
  createdAt: string;
  /**
     * `None` means the project sits at the top level of the sidebar.
     * @nullable
     */
  folderId?: string | null;
  id: string;
  /** Loaded in a second query, never a column on `projects`. */
  metadata: MetadataValue[];
  name: string;
  updatedAt: string;
}

export interface ProjectFolderInput {
  /**
     * Omitted or null files the project at the top level.
     * @nullable
     */
  folderId?: string | null;
}

export interface ProjectInput {
  /**
     * Optional client-selected entity id; sync uses a separate mutation id for safe replay.
     * @nullable
     */
  id?: string | null;
  name: string;
}

export interface Reminder {
  remindAt: string;
  taskId: string;
}

export interface SyncOperation {
  body: unknown;
  expectedVersion: number;
  id: string;
  method: string;
  url: string;
}

export interface Task {
  completed: boolean;
  createdAt: string;
  /**
     * Local wall-clock date and time, `YYYY-MM-DDTHH:MM`.
     * @nullable
     */
  dueOn?: string | null;
  id: string;
  /**
     * Local wall-clock date and time, `YYYY-MM-DDTHH:MM`.
     * @nullable
     */
  plannedFor?: string | null;
  /** Name of the owning project, joined for display. */
  project: string;
  projectId: string;
  /** @nullable */
  repeatWeekday?: number | null;
  title: string;
  updatedAt: string;
}

export interface SyncSnapshot {
  fields: MetadataField[];
  folders: Folder[];
  projects: Project[];
  tasks: Task[];
  versions: BTreeMap;
}

export interface SyncReply {
  /** Only versions changed by this operation, not unrelated changes from another device. */
  changes: BTreeMap;
  snapshot: SyncSnapshot;
}

export interface TaskInput {
  completed: boolean;
  /**
     * Local wall-clock date and time, `YYYY-MM-DDTHH:MM`.
     * @nullable
     */
  dueOn?: string | null;
  id: string;
  /**
     * Local wall-clock date and time, `YYYY-MM-DDTHH:MM`.
     * @nullable
     */
  plannedFor?: string | null;
  projectId: string;
  /** @nullable */
  repeatWeekday?: number | null;
  title: string;
}

export interface ToggleInput {
  completed: boolean;
  /**
     * If supplied, must equal `next:{taskId}`; all clients share one successor.
     * @nullable
     */
  nextId?: string | null;
}

export interface ToggleResult {
  nextTask?: null | Task;
  task: Task;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type listFoldersResponse200 = {
  data: Folder[]
  status: 200
}

export type listFoldersResponseSuccess = (listFoldersResponse200) & {
  headers: Headers;
};
;

export type listFoldersResponse = (listFoldersResponseSuccess)

export const getListFoldersUrl = () => {




  return `/api/folders`
}

export const listFolders = async ( options?: Parameters<typeof apiFetch>[1]): Promise<listFoldersResponse> => {

  return apiFetch<listFoldersResponse>(getListFoldersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFoldersQueryKey = () => {
    return [
    `/api/folders`
    ] as const;
    }


export const getListFoldersQueryOptions = <TData = Awaited<ReturnType<typeof listFolders>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFoldersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFolders>>> = ({ signal }) => listFolders({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof listFolders>>>
export type ListFoldersQueryError = unknown



export function createListFolders<TData = Awaited<ReturnType<typeof listFolders>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListFoldersQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createListFolders} query
 */
export const invalidateListFolders = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListFoldersQueryKey() }, options);

  return queryClient;
}





export type createFolderResponse201 = {
  data: Folder
  status: 201
}

export type createFolderResponse400 = {
  data: string
  status: 400
}

export type createFolderResponse404 = {
  data: string
  status: 404
}

export type createFolderResponseSuccess = (createFolderResponse201) & {
  headers: Headers;
};
export type createFolderResponseError = (createFolderResponse400 | createFolderResponse404) & {
  headers: Headers;
};

export type createFolderResponse = (createFolderResponseSuccess | createFolderResponseError)

export const getCreateFolderUrl = () => {




  return `/api/folders`
}

export const createFolder = async (folderInput: FolderInput, options?: Parameters<typeof apiFetch>[1]): Promise<createFolderResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<createFolderResponse>(getCreateFolderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(folderInput)
  }
);}





export const getCreateFolderMutationKey = () => ['createFolder'] as const;

export const getCreateFolderMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,CreateFolderMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,CreateFolderMutationVariables, TContext> => {

const mutationKey = getCreateFolderMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFolder>>, CreateFolderMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createFolder(data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof createFolder>>, variables: CreateFolderMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListFoldersQueryKey(), getListProjectsQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type CreateFolderMutationResult = NonNullable<Awaited<ReturnType<typeof createFolder>>>
    export type CreateFolderMutationBody = FolderInput
    export type CreateFolderMutationError = string
    export type CreateFolderMutationVariables = {data: FolderInput}

    export const createCreateFolder = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,CreateFolderMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createFolder>>,
        TError,
        CreateFolderMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getCreateFolderMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type updateFolderResponse200 = {
  data: Folder
  status: 200
}

export type updateFolderResponse400 = {
  data: string
  status: 400
}

export type updateFolderResponse404 = {
  data: string
  status: 404
}

export type updateFolderResponseSuccess = (updateFolderResponse200) & {
  headers: Headers;
};
export type updateFolderResponseError = (updateFolderResponse400 | updateFolderResponse404) & {
  headers: Headers;
};

export type updateFolderResponse = (updateFolderResponseSuccess | updateFolderResponseError)

export const getUpdateFolderUrl = (id: string,) => {




  return `/api/folders/${id}`
}

export const updateFolder = async (id: string,
    folderInput: FolderInput, options?: Parameters<typeof apiFetch>[1]): Promise<updateFolderResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<updateFolderResponse>(getUpdateFolderUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(folderInput)
  }
);}





export const getUpdateFolderMutationKey = () => ['updateFolder'] as const;

export const getUpdateFolderMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateFolder>>, TError,UpdateFolderMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof updateFolder>>, TError,UpdateFolderMutationVariables, TContext> => {

const mutationKey = getUpdateFolderMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFolder>>, UpdateFolderMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateFolder(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof updateFolder>>, variables: UpdateFolderMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListFoldersQueryKey(), getListProjectsQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type UpdateFolderMutationResult = NonNullable<Awaited<ReturnType<typeof updateFolder>>>
    export type UpdateFolderMutationBody = FolderInput
    export type UpdateFolderMutationError = string
    export type UpdateFolderMutationVariables = {id: string;data: FolderInput}

    export const createUpdateFolder = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateFolder>>, TError,UpdateFolderMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updateFolder>>,
        TError,
        UpdateFolderMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getUpdateFolderMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type deleteFolderResponse204 = {
  data: void
  status: 204
}

export type deleteFolderResponse404 = {
  data: string
  status: 404
}

export type deleteFolderResponseSuccess = (deleteFolderResponse204) & {
  headers: Headers;
};
export type deleteFolderResponseError = (deleteFolderResponse404) & {
  headers: Headers;
};

export type deleteFolderResponse = (deleteFolderResponseSuccess | deleteFolderResponseError)

export const getDeleteFolderUrl = (id: string,) => {




  return `/api/folders/${id}`
}

export const deleteFolder = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<deleteFolderResponse> => {

  return apiFetch<deleteFolderResponse>(getDeleteFolderUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFolderMutationKey = () => ['deleteFolder'] as const;

export const getDeleteFolderMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,DeleteFolderMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,DeleteFolderMutationVariables, TContext> => {

const mutationKey = getDeleteFolderMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFolder>>, DeleteFolderMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteFolder(id,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof deleteFolder>>, variables: DeleteFolderMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListFoldersQueryKey(), getListProjectsQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type DeleteFolderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFolder>>>

    export type DeleteFolderMutationError = string
    export type DeleteFolderMutationVariables = {id: string}

    export const createDeleteFolder = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,DeleteFolderMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteFolder>>,
        TError,
        DeleteFolderMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getDeleteFolderMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type listMetadataFieldsResponse200 = {
  data: MetadataField[]
  status: 200
}

export type listMetadataFieldsResponseSuccess = (listMetadataFieldsResponse200) & {
  headers: Headers;
};
;

export type listMetadataFieldsResponse = (listMetadataFieldsResponseSuccess)

export const getListMetadataFieldsUrl = () => {




  return `/api/metadata-fields`
}

export const listMetadataFields = async ( options?: Parameters<typeof apiFetch>[1]): Promise<listMetadataFieldsResponse> => {

  return apiFetch<listMetadataFieldsResponse>(getListMetadataFieldsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMetadataFieldsQueryKey = () => {
    return [
    `/api/metadata-fields`
    ] as const;
    }


export const getListMetadataFieldsQueryOptions = <TData = Awaited<ReturnType<typeof listMetadataFields>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listMetadataFields>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMetadataFieldsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMetadataFields>>> = ({ signal }) => listMetadataFields({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listMetadataFields>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMetadataFieldsQueryResult = NonNullable<Awaited<ReturnType<typeof listMetadataFields>>>
export type ListMetadataFieldsQueryError = unknown



export function createListMetadataFields<TData = Awaited<ReturnType<typeof listMetadataFields>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listMetadataFields>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListMetadataFieldsQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createListMetadataFields} query
 */
export const invalidateListMetadataFields = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListMetadataFieldsQueryKey() }, options);

  return queryClient;
}





export type createMetadataFieldResponse201 = {
  data: MetadataField
  status: 201
}

export type createMetadataFieldResponse400 = {
  data: string
  status: 400
}

export type createMetadataFieldResponseSuccess = (createMetadataFieldResponse201) & {
  headers: Headers;
};
export type createMetadataFieldResponseError = (createMetadataFieldResponse400) & {
  headers: Headers;
};

export type createMetadataFieldResponse = (createMetadataFieldResponseSuccess | createMetadataFieldResponseError)

export const getCreateMetadataFieldUrl = () => {




  return `/api/metadata-fields`
}

export const createMetadataField = async (metadataFieldInput: MetadataFieldInput, options?: Parameters<typeof apiFetch>[1]): Promise<createMetadataFieldResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<createMetadataFieldResponse>(getCreateMetadataFieldUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(metadataFieldInput)
  }
);}





export const getCreateMetadataFieldMutationKey = () => ['createMetadataField'] as const;

export const getCreateMetadataFieldMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createMetadataField>>, TError,CreateMetadataFieldMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof createMetadataField>>, TError,CreateMetadataFieldMutationVariables, TContext> => {

const mutationKey = getCreateMetadataFieldMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMetadataField>>, CreateMetadataFieldMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createMetadataField(data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof createMetadataField>>, variables: CreateMetadataFieldMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type CreateMetadataFieldMutationResult = NonNullable<Awaited<ReturnType<typeof createMetadataField>>>
    export type CreateMetadataFieldMutationBody = MetadataFieldInput
    export type CreateMetadataFieldMutationError = string
    export type CreateMetadataFieldMutationVariables = {data: MetadataFieldInput}

    export const createCreateMetadataField = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createMetadataField>>, TError,CreateMetadataFieldMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createMetadataField>>,
        TError,
        CreateMetadataFieldMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getCreateMetadataFieldMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type updateMetadataFieldResponse200 = {
  data: MetadataField
  status: 200
}

export type updateMetadataFieldResponse400 = {
  data: string
  status: 400
}

export type updateMetadataFieldResponse404 = {
  data: string
  status: 404
}

export type updateMetadataFieldResponseSuccess = (updateMetadataFieldResponse200) & {
  headers: Headers;
};
export type updateMetadataFieldResponseError = (updateMetadataFieldResponse400 | updateMetadataFieldResponse404) & {
  headers: Headers;
};

export type updateMetadataFieldResponse = (updateMetadataFieldResponseSuccess | updateMetadataFieldResponseError)

export const getUpdateMetadataFieldUrl = (id: string,) => {




  return `/api/metadata-fields/${id}`
}

export const updateMetadataField = async (id: string,
    metadataFieldUpdate: MetadataFieldUpdate, options?: Parameters<typeof apiFetch>[1]): Promise<updateMetadataFieldResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<updateMetadataFieldResponse>(getUpdateMetadataFieldUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(metadataFieldUpdate)
  }
);}





export const getUpdateMetadataFieldMutationKey = () => ['updateMetadataField'] as const;

export const getUpdateMetadataFieldMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateMetadataField>>, TError,UpdateMetadataFieldMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof updateMetadataField>>, TError,UpdateMetadataFieldMutationVariables, TContext> => {

const mutationKey = getUpdateMetadataFieldMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMetadataField>>, UpdateMetadataFieldMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateMetadataField(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof updateMetadataField>>, variables: UpdateMetadataFieldMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type UpdateMetadataFieldMutationResult = NonNullable<Awaited<ReturnType<typeof updateMetadataField>>>
    export type UpdateMetadataFieldMutationBody = MetadataFieldUpdate
    export type UpdateMetadataFieldMutationError = string
    export type UpdateMetadataFieldMutationVariables = {id: string;data: MetadataFieldUpdate}

    export const createUpdateMetadataField = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateMetadataField>>, TError,UpdateMetadataFieldMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updateMetadataField>>,
        TError,
        UpdateMetadataFieldMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getUpdateMetadataFieldMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type deleteMetadataFieldResponse204 = {
  data: void
  status: 204
}

export type deleteMetadataFieldResponse404 = {
  data: string
  status: 404
}

export type deleteMetadataFieldResponseSuccess = (deleteMetadataFieldResponse204) & {
  headers: Headers;
};
export type deleteMetadataFieldResponseError = (deleteMetadataFieldResponse404) & {
  headers: Headers;
};

export type deleteMetadataFieldResponse = (deleteMetadataFieldResponseSuccess | deleteMetadataFieldResponseError)

export const getDeleteMetadataFieldUrl = (id: string,) => {




  return `/api/metadata-fields/${id}`
}

export const deleteMetadataField = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<deleteMetadataFieldResponse> => {

  return apiFetch<deleteMetadataFieldResponse>(getDeleteMetadataFieldUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteMetadataFieldMutationKey = () => ['deleteMetadataField'] as const;

export const getDeleteMetadataFieldMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteMetadataField>>, TError,DeleteMetadataFieldMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteMetadataField>>, TError,DeleteMetadataFieldMutationVariables, TContext> => {

const mutationKey = getDeleteMetadataFieldMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMetadataField>>, DeleteMetadataFieldMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteMetadataField(id,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof deleteMetadataField>>, variables: DeleteMetadataFieldMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type DeleteMetadataFieldMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMetadataField>>>

    export type DeleteMetadataFieldMutationError = string
    export type DeleteMetadataFieldMutationVariables = {id: string}

    export const createDeleteMetadataField = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteMetadataField>>, TError,DeleteMetadataFieldMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteMetadataField>>,
        TError,
        DeleteMetadataFieldMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getDeleteMetadataFieldMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type listProjectsResponse200 = {
  data: Project[]
  status: 200
}

export type listProjectsResponseSuccess = (listProjectsResponse200) & {
  headers: Headers;
};
;

export type listProjectsResponse = (listProjectsResponseSuccess)

export const getListProjectsUrl = () => {




  return `/api/projects`
}

export const listProjects = async ( options?: Parameters<typeof apiFetch>[1]): Promise<listProjectsResponse> => {

  return apiFetch<listProjectsResponse>(getListProjectsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProjectsQueryKey = () => {
    return [
    `/api/projects`
    ] as const;
    }


export const getListProjectsQueryOptions = <TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProjectsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjects>>> = ({ signal }) => listProjects({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjects>>>
export type ListProjectsQueryError = unknown



export function createListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListProjectsQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createListProjects} query
 */
export const invalidateListProjects = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListProjectsQueryKey() }, options);

  return queryClient;
}





export type createProjectResponse201 = {
  data: Project
  status: 201
}

export type createProjectResponse400 = {
  data: string
  status: 400
}

export type createProjectResponseSuccess = (createProjectResponse201) & {
  headers: Headers;
};
export type createProjectResponseError = (createProjectResponse400) & {
  headers: Headers;
};

export type createProjectResponse = (createProjectResponseSuccess | createProjectResponseError)

export const getCreateProjectUrl = () => {




  return `/api/projects`
}

export const createProject = async (projectInput: ProjectInput, options?: Parameters<typeof apiFetch>[1]): Promise<createProjectResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<createProjectResponse>(getCreateProjectUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(projectInput)
  }
);}





export const getCreateProjectMutationKey = () => ['createProject'] as const;

export const getCreateProjectMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,CreateProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,CreateProjectMutationVariables, TContext> => {

const mutationKey = getCreateProjectMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, CreateProjectMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createProject(data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof createProject>>, variables: CreateProjectMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = ProjectInput
    export type CreateProjectMutationError = string
    export type CreateProjectMutationVariables = {data: ProjectInput}

    export const createCreateProject = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,CreateProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        CreateProjectMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getCreateProjectMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type getProjectResponse200 = {
  data: Project
  status: 200
}

export type getProjectResponse404 = {
  data: string
  status: 404
}

export type getProjectResponseSuccess = (getProjectResponse200) & {
  headers: Headers;
};
export type getProjectResponseError = (getProjectResponse404) & {
  headers: Headers;
};

export type getProjectResponse = (getProjectResponseSuccess | getProjectResponseError)

export const getGetProjectUrl = (id: string,) => {




  return `/api/projects/${id}`
}

export const getProject = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<getProjectResponse> => {

  return apiFetch<getProjectResponse>(getGetProjectUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProjectQueryKey = (id: string,) => {
    return [
    `/api/projects/${id}`
    ] as const;
    }


export const getGetProjectQueryOptions = <TData = Awaited<ReturnType<typeof getProject>>, TError = string>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({ signal }) => getProject(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getProject>>>
export type GetProjectQueryError = string



export function createGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = string>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getGetProjectQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createGetProject} query
 */
export const invalidateGetProject = async (
 queryClient: QueryClient, id: string, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetProjectQueryKey(id) }, options);

  return queryClient;
}





export type updateProjectResponse200 = {
  data: Project
  status: 200
}

export type updateProjectResponse400 = {
  data: string
  status: 400
}

export type updateProjectResponse404 = {
  data: string
  status: 404
}

export type updateProjectResponseSuccess = (updateProjectResponse200) & {
  headers: Headers;
};
export type updateProjectResponseError = (updateProjectResponse400 | updateProjectResponse404) & {
  headers: Headers;
};

export type updateProjectResponse = (updateProjectResponseSuccess | updateProjectResponseError)

export const getUpdateProjectUrl = (id: string,) => {




  return `/api/projects/${id}`
}

export const updateProject = async (id: string,
    projectInput: ProjectInput, options?: Parameters<typeof apiFetch>[1]): Promise<updateProjectResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<updateProjectResponse>(getUpdateProjectUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(projectInput)
  }
);}





export const getUpdateProjectMutationKey = () => ['updateProject'] as const;

export const getUpdateProjectMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,UpdateProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,UpdateProjectMutationVariables, TContext> => {

const mutationKey = getUpdateProjectMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProject>>, UpdateProjectMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateProject(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof updateProject>>, variables: UpdateProjectMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>
    export type UpdateProjectMutationBody = ProjectInput
    export type UpdateProjectMutationError = string
    export type UpdateProjectMutationVariables = {id: string;data: ProjectInput}

    export const createUpdateProject = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,UpdateProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updateProject>>,
        TError,
        UpdateProjectMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getUpdateProjectMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type deleteProjectResponse204 = {
  data: void
  status: 204
}

export type deleteProjectResponse400 = {
  data: string
  status: 400
}

export type deleteProjectResponse404 = {
  data: string
  status: 404
}

export type deleteProjectResponseSuccess = (deleteProjectResponse204) & {
  headers: Headers;
};
export type deleteProjectResponseError = (deleteProjectResponse400 | deleteProjectResponse404) & {
  headers: Headers;
};

export type deleteProjectResponse = (deleteProjectResponseSuccess | deleteProjectResponseError)

export const getDeleteProjectUrl = (id: string,) => {




  return `/api/projects/${id}`
}

export const deleteProject = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<deleteProjectResponse> => {

  return apiFetch<deleteProjectResponse>(getDeleteProjectUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteProjectMutationKey = () => ['deleteProject'] as const;

export const getDeleteProjectMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,DeleteProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,DeleteProjectMutationVariables, TContext> => {

const mutationKey = getDeleteProjectMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, DeleteProjectMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteProject(id,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof deleteProject>>, variables: DeleteProjectMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>

    export type DeleteProjectMutationError = string
    export type DeleteProjectMutationVariables = {id: string}

    export const createDeleteProject = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,DeleteProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteProject>>,
        TError,
        DeleteProjectMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getDeleteProjectMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type moveProjectResponse200 = {
  data: Project
  status: 200
}

export type moveProjectResponse400 = {
  data: string
  status: 400
}

export type moveProjectResponse404 = {
  data: string
  status: 404
}

export type moveProjectResponseSuccess = (moveProjectResponse200) & {
  headers: Headers;
};
export type moveProjectResponseError = (moveProjectResponse400 | moveProjectResponse404) & {
  headers: Headers;
};

export type moveProjectResponse = (moveProjectResponseSuccess | moveProjectResponseError)

export const getMoveProjectUrl = (id: string,) => {




  return `/api/projects/${id}/folder`
}

export const moveProject = async (id: string,
    projectFolderInput: ProjectFolderInput, options?: Parameters<typeof apiFetch>[1]): Promise<moveProjectResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<moveProjectResponse>(getMoveProjectUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(projectFolderInput)
  }
);}





export const getMoveProjectMutationKey = () => ['moveProject'] as const;

export const getMoveProjectMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof moveProject>>, TError,MoveProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof moveProject>>, TError,MoveProjectMutationVariables, TContext> => {

const mutationKey = getMoveProjectMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveProject>>, MoveProjectMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  moveProject(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof moveProject>>, variables: MoveProjectMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type MoveProjectMutationResult = NonNullable<Awaited<ReturnType<typeof moveProject>>>
    export type MoveProjectMutationBody = ProjectFolderInput
    export type MoveProjectMutationError = string
    export type MoveProjectMutationVariables = {id: string;data: ProjectFolderInput}

    export const createMoveProject = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof moveProject>>, TError,MoveProjectMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof moveProject>>,
        TError,
        MoveProjectMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getMoveProjectMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type setProjectMetadataResponse204 = {
  data: void
  status: 204
}

export type setProjectMetadataResponse400 = {
  data: string
  status: 400
}

export type setProjectMetadataResponse404 = {
  data: string
  status: 404
}

export type setProjectMetadataResponseSuccess = (setProjectMetadataResponse204) & {
  headers: Headers;
};
export type setProjectMetadataResponseError = (setProjectMetadataResponse400 | setProjectMetadataResponse404) & {
  headers: Headers;
};

export type setProjectMetadataResponse = (setProjectMetadataResponseSuccess | setProjectMetadataResponseError)

export const getSetProjectMetadataUrl = (id: string,
    fieldId: string,) => {




  return `/api/projects/${id}/metadata/${fieldId}`
}

export const setProjectMetadata = async (id: string,
    fieldId: string,
    metadataValueInput: MetadataValueInput, options?: Parameters<typeof apiFetch>[1]): Promise<setProjectMetadataResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<setProjectMetadataResponse>(getSetProjectMetadataUrl(id,fieldId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(metadataValueInput)
  }
);}





export const getSetProjectMetadataMutationKey = () => ['setProjectMetadata'] as const;

export const getSetProjectMetadataMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof setProjectMetadata>>, TError,SetProjectMetadataMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof setProjectMetadata>>, TError,SetProjectMetadataMutationVariables, TContext> => {

const mutationKey = getSetProjectMetadataMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setProjectMetadata>>, SetProjectMetadataMutationVariables> = (props) => {
          const {id,fieldId,data} = props ?? {};

          return  setProjectMetadata(id,fieldId,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof setProjectMetadata>>, variables: SetProjectMetadataMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ predicate: (query) => [getListProjectsQueryKey(), getListTasksQueryKey()].some((queryKey) => matchQuery({ queryKey }, query)) });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type SetProjectMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof setProjectMetadata>>>
    export type SetProjectMetadataMutationBody = MetadataValueInput
    export type SetProjectMetadataMutationError = string
    export type SetProjectMetadataMutationVariables = {id: string;fieldId: string;data: MetadataValueInput}

    export const createSetProjectMetadata = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof setProjectMetadata>>, TError,SetProjectMetadataMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof setProjectMetadata>>,
        TError,
        SetProjectMetadataMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getSetProjectMetadataMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type getReminderResponse200 = {
  data: Reminder
  status: 200
}

export type getReminderResponse404 = {
  data: string
  status: 404
}

export type getReminderResponseSuccess = (getReminderResponse200) & {
  headers: Headers;
};
export type getReminderResponseError = (getReminderResponse404) & {
  headers: Headers;
};

export type getReminderResponse = (getReminderResponseSuccess | getReminderResponseError)

export const getGetReminderUrl = (id: string,) => {




  return `/api/reminders/${id}`
}

export const getReminder = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<getReminderResponse> => {

  return apiFetch<getReminderResponse>(getGetReminderUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReminderQueryKey = (id: string,) => {
    return [
    `/api/reminders/${id}`
    ] as const;
    }


export const getGetReminderQueryOptions = <TData = Awaited<ReturnType<typeof getReminder>>, TError = string>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getReminder>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReminderQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReminder>>> = ({ signal }) => getReminder(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getReminder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReminderQueryResult = NonNullable<Awaited<ReturnType<typeof getReminder>>>
export type GetReminderQueryError = string



export function createGetReminder<TData = Awaited<ReturnType<typeof getReminder>>, TError = string>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getReminder>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getGetReminderQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createGetReminder} query
 */
export const invalidateGetReminder = async (
 queryClient: QueryClient, id: string, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetReminderQueryKey(id) }, options);

  return queryClient;
}





export type getSyncSnapshotResponse200 = {
  data: SyncSnapshot
  status: 200
}

export type getSyncSnapshotResponseSuccess = (getSyncSnapshotResponse200) & {
  headers: Headers;
};
;

export type getSyncSnapshotResponse = (getSyncSnapshotResponseSuccess)

export const getGetSyncSnapshotUrl = () => {




  return `/api/sync`
}

export const getSyncSnapshot = async ( options?: Parameters<typeof apiFetch>[1]): Promise<getSyncSnapshotResponse> => {

  return apiFetch<getSyncSnapshotResponse>(getGetSyncSnapshotUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSyncSnapshotQueryKey = () => {
    return [
    `/api/sync`
    ] as const;
    }


export const getGetSyncSnapshotQueryOptions = <TData = Awaited<ReturnType<typeof getSyncSnapshot>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSyncSnapshot>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSyncSnapshotQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSyncSnapshot>>> = ({ signal }) => getSyncSnapshot({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getSyncSnapshot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSyncSnapshotQueryResult = NonNullable<Awaited<ReturnType<typeof getSyncSnapshot>>>
export type GetSyncSnapshotQueryError = unknown



export function createGetSyncSnapshot<TData = Awaited<ReturnType<typeof getSyncSnapshot>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSyncSnapshot>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getGetSyncSnapshotQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createGetSyncSnapshot} query
 */
export const invalidateGetSyncSnapshot = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetSyncSnapshotQueryKey() }, options);

  return queryClient;
}





export type applySyncOperationResponse200 = {
  data: SyncReply
  status: 200
}

export type applySyncOperationResponse400 = {
  data: string
  status: 400
}

export type applySyncOperationResponse404 = {
  data: string
  status: 404
}

export type applySyncOperationResponse409 = {
  data: string
  status: 409
}

export type applySyncOperationResponseSuccess = (applySyncOperationResponse200) & {
  headers: Headers;
};
export type applySyncOperationResponseError = (applySyncOperationResponse400 | applySyncOperationResponse404 | applySyncOperationResponse409) & {
  headers: Headers;
};

export type applySyncOperationResponse = (applySyncOperationResponseSuccess | applySyncOperationResponseError)

export const getApplySyncOperationUrl = () => {




  return `/api/sync`
}

export const applySyncOperation = async (syncOperation: SyncOperation, options?: Parameters<typeof apiFetch>[1]): Promise<applySyncOperationResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<applySyncOperationResponse>(getApplySyncOperationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(syncOperation)
  }
);}





export const getApplySyncOperationMutationKey = () => ['applySyncOperation'] as const;

export const getApplySyncOperationMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof applySyncOperation>>, TError,ApplySyncOperationMutationVariables, TContext>, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof applySyncOperation>>, TError,ApplySyncOperationMutationVariables, TContext> => {

const mutationKey = getApplySyncOperationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applySyncOperation>>, ApplySyncOperationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  applySyncOperation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApplySyncOperationMutationResult = NonNullable<Awaited<ReturnType<typeof applySyncOperation>>>
    export type ApplySyncOperationMutationBody = SyncOperation
    export type ApplySyncOperationMutationError = string
    export type ApplySyncOperationMutationVariables = {data: SyncOperation}

    export const createApplySyncOperation = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof applySyncOperation>>, TError,ApplySyncOperationMutationVariables, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof applySyncOperation>>,
        TError,
        ApplySyncOperationMutationVariables,
        TContext
      > => {
      return createMutation(() => ({ ...getApplySyncOperationMutationOptions(options?.()) }), queryClient);
    }

export type listTasksResponse200 = {
  data: Task[]
  status: 200
}

export type listTasksResponseSuccess = (listTasksResponse200) & {
  headers: Headers;
};
;

export type listTasksResponse = (listTasksResponseSuccess)

export const getListTasksUrl = () => {




  return `/api/tasks`
}

export const listTasks = async ( options?: Parameters<typeof apiFetch>[1]): Promise<listTasksResponse> => {

  return apiFetch<listTasksResponse>(getListTasksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTasksQueryKey = () => {
    return [
    `/api/tasks`
    ] as const;
    }


export const getListTasksQueryOptions = <TData = Awaited<ReturnType<typeof listTasks>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTasksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasks>>> = ({ signal }) => listTasks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTasksQueryResult = NonNullable<Awaited<ReturnType<typeof listTasks>>>
export type ListTasksQueryError = unknown



export function createListTasks<TData = Awaited<ReturnType<typeof listTasks>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListTasksQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createListTasks} query
 */
export const invalidateListTasks = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() }, options);

  return queryClient;
}





export type createTaskResponse201 = {
  data: Task
  status: 201
}

export type createTaskResponse400 = {
  data: string
  status: 400
}

export type createTaskResponseSuccess = (createTaskResponse201) & {
  headers: Headers;
};
export type createTaskResponseError = (createTaskResponse400) & {
  headers: Headers;
};

export type createTaskResponse = (createTaskResponseSuccess | createTaskResponseError)

export const getCreateTaskUrl = () => {




  return `/api/tasks`
}

export const createTask = async (taskInput: TaskInput, options?: Parameters<typeof apiFetch>[1]): Promise<createTaskResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<createTaskResponse>(getCreateTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(taskInput)
  }
);}





export const getCreateTaskMutationKey = () => ['createTask'] as const;

export const getCreateTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,CreateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,CreateTaskMutationVariables, TContext> => {

const mutationKey = getCreateTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTask>>, CreateTaskMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTask(data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof createTask>>, variables: CreateTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type CreateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof createTask>>>
    export type CreateTaskMutationBody = TaskInput
    export type CreateTaskMutationError = string
    export type CreateTaskMutationVariables = {data: TaskInput}

    export const createCreateTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,CreateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createTask>>,
        TError,
        CreateTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getCreateTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type getTaskResponse200 = {
  data: Task
  status: 200
}

export type getTaskResponse404 = {
  data: string
  status: 404
}

export type getTaskResponseSuccess = (getTaskResponse200) & {
  headers: Headers;
};
export type getTaskResponseError = (getTaskResponse404) & {
  headers: Headers;
};

export type getTaskResponse = (getTaskResponseSuccess | getTaskResponseError)

export const getGetTaskUrl = (id: string,) => {




  return `/api/tasks/${id}`
}

export const getTask = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<getTaskResponse> => {

  return apiFetch<getTaskResponse>(getGetTaskUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTaskQueryKey = (id: string,) => {
    return [
    `/api/tasks/${id}`
    ] as const;
    }


export const getGetTaskQueryOptions = <TData = Awaited<ReturnType<typeof getTask>>, TError = string>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({ signal }) => getTask(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getTask>>>
export type GetTaskQueryError = string



export function createGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = string>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getGetTaskQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createGetTask} query
 */
export const invalidateGetTask = async (
 queryClient: QueryClient, id: string, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetTaskQueryKey(id) }, options);

  return queryClient;
}





export type updateTaskResponse200 = {
  data: Task
  status: 200
}

export type updateTaskResponse400 = {
  data: string
  status: 400
}

export type updateTaskResponse404 = {
  data: string
  status: 404
}

export type updateTaskResponseSuccess = (updateTaskResponse200) & {
  headers: Headers;
};
export type updateTaskResponseError = (updateTaskResponse400 | updateTaskResponse404) & {
  headers: Headers;
};

export type updateTaskResponse = (updateTaskResponseSuccess | updateTaskResponseError)

export const getUpdateTaskUrl = (id: string,) => {




  return `/api/tasks/${id}`
}

export const updateTask = async (id: string,
    taskInput: TaskInput, options?: Parameters<typeof apiFetch>[1]): Promise<updateTaskResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<updateTaskResponse>(getUpdateTaskUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(taskInput)
  }
);}





export const getUpdateTaskMutationKey = () => ['updateTask'] as const;

export const getUpdateTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,UpdateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,UpdateTaskMutationVariables, TContext> => {

const mutationKey = getUpdateTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTask>>, UpdateTaskMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateTask(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof updateTask>>, variables: UpdateTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type UpdateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof updateTask>>>
    export type UpdateTaskMutationBody = TaskInput
    export type UpdateTaskMutationError = string
    export type UpdateTaskMutationVariables = {id: string;data: TaskInput}

    export const createUpdateTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,UpdateTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updateTask>>,
        TError,
        UpdateTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getUpdateTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type deleteTaskResponse204 = {
  data: void
  status: 204
}

export type deleteTaskResponse404 = {
  data: string
  status: 404
}

export type deleteTaskResponseSuccess = (deleteTaskResponse204) & {
  headers: Headers;
};
export type deleteTaskResponseError = (deleteTaskResponse404) & {
  headers: Headers;
};

export type deleteTaskResponse = (deleteTaskResponseSuccess | deleteTaskResponseError)

export const getDeleteTaskUrl = (id: string,) => {




  return `/api/tasks/${id}`
}

export const deleteTask = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<deleteTaskResponse> => {

  return apiFetch<deleteTaskResponse>(getDeleteTaskUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTaskMutationKey = () => ['deleteTask'] as const;

export const getDeleteTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,DeleteTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,DeleteTaskMutationVariables, TContext> => {

const mutationKey = getDeleteTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTask>>, DeleteTaskMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteTask(id,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof deleteTask>>, variables: DeleteTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type DeleteTaskMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTask>>>

    export type DeleteTaskMutationError = string
    export type DeleteTaskMutationVariables = {id: string}

    export const createDeleteTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,DeleteTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteTask>>,
        TError,
        DeleteTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getDeleteTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type toggleTaskResponse200 = {
  data: ToggleResult
  status: 200
}

export type toggleTaskResponse400 = {
  data: string
  status: 400
}

export type toggleTaskResponse404 = {
  data: string
  status: 404
}

export type toggleTaskResponseSuccess = (toggleTaskResponse200) & {
  headers: Headers;
};
export type toggleTaskResponseError = (toggleTaskResponse400 | toggleTaskResponse404) & {
  headers: Headers;
};

export type toggleTaskResponse = (toggleTaskResponseSuccess | toggleTaskResponseError)

export const getToggleTaskUrl = (id: string,) => {




  return `/api/tasks/${id}/toggle`
}

export const toggleTask = async (id: string,
    toggleInput: ToggleInput, options?: Parameters<typeof apiFetch>[1]): Promise<toggleTaskResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<toggleTaskResponse>(getToggleTaskUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(toggleInput)
  }
);}





export const getToggleTaskMutationKey = () => ['toggleTask'] as const;

export const getToggleTaskMutationOptions = <TError = string,
    TContext = unknown>(queryClient: QueryClient, options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof toggleTask>>, TError,ToggleTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
): CreateMutationOptions<Awaited<ReturnType<typeof toggleTask>>, TError,ToggleTaskMutationVariables, TContext> => {

const mutationKey = getToggleTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleTask>>, ToggleTaskMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  toggleTask(id,data,requestOptions)
        }

  const onSuccess = (data: Awaited<ReturnType<typeof toggleTask>>, variables: ToggleTaskMutationVariables, onMutateResult: TContext, context: MutationFunctionContext) => {
        if (!options?.skipInvalidation) {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey() });
        }
        mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
      };




  return  { ...mutationOptions, mutationFn, onSuccess }}

    export type ToggleTaskMutationResult = NonNullable<Awaited<ReturnType<typeof toggleTask>>>
    export type ToggleTaskMutationBody = ToggleInput
    export type ToggleTaskMutationError = string
    export type ToggleTaskMutationVariables = {id: string;data: ToggleInput}

    export const createToggleTask = <TError = string,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof toggleTask>>, TError,ToggleTaskMutationVariables, TContext>, skipInvalidation?: boolean, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof toggleTask>>,
        TError,
        ToggleTaskMutationVariables,
        TContext
      > => {
      const backupQueryClient = useQueryClient(queryClient?.());
      return createMutation(() => ({ ...getToggleTaskMutationOptions(backupQueryClient, options?.()) }), queryClient);
    }

export type healthResponse200 = {
  data: void
  status: 200
}

export type healthResponse503 = {
  data: string
  status: 503
}

export type healthResponseSuccess = (healthResponse200) & {
  headers: Headers;
};
export type healthResponseError = (healthResponse503) & {
  headers: Headers;
};

export type healthResponse = (healthResponseSuccess | healthResponseError)

export const getHealthUrl = () => {




  return `/health`
}

export const health = async ( options?: Parameters<typeof apiFetch>[1]): Promise<healthResponse> => {

  return apiFetch<healthResponse>(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthQueryOptions = <TData = Awaited<ReturnType<typeof health>>, TError = string>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) => health({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>
export type HealthQueryError = string



export function createHealth<TData = Awaited<ReturnType<typeof health>>, TError = string>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getHealthQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}


/**
 * @summary Invalidates the {@link createHealth} query
 */
export const invalidateHealth = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getHealthQueryKey() }, options);

  return queryClient;
}
